### ISSUE TITLE
Static page for /new

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1101]
Good afternoon!

As discussed on Zulip, we would like a landing page for users adding a new record. So, instead of getting the new record form immediately upon clicking "Add Content", they should instead be redirected to an updated version of https://fairsharing.org/new/ .

We discussed having a shorter form of /new at the top of the new record form, however while I agree in principle with this idea, we need the https://fairsharing.org/new/ URL to point to a static page, simply because this is a pre-existing page that we have been pointing users to for some time to help them decide if they should submit to us.

Right now, you can't get to https://fairsharing.org/new/ in the rebuild unless you're logged in, and because it is an informational page for users, making it a normal static page would solve this problem.

Please let me know when you have text for me that is copied from the existing https://fairsharing.org/new/ and I will update it for the rebuild. As has been suggested, making it shorter and quick to read will help ensure that users read it. We can always link out to additional user documentation, currently being written.

Thanks!

**Comment by knirirr** [comment]
For this, the routes (index.js ?) will need to be modified so that the existing /new is replaced by another route (/create might do the trick) and a new /new is created which points at a static page ( views/Records/New.vue for example) containing the text that's currently on https://fairsharing.org/new/ (which must then be modified).
