### ISSUE TITLE
Restructure the user profile edit page

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1267]
With the addition of the organisation search box in the user profile edit page, we need to restructure the edit form. There is an edit form below the update button and appears to update that section independently, for instance. We just need to make the page look more integrated and update at the same time.

**Comment by knirirr** [comment]
Here is some feedback from a user concerning this edit page:

> Is more of a "non-intuitive" rather than a technically faulty issue, in the "Organisations" part of the profile edit, the left shows "Available organisations" and the right, "user organisations" with a green button right below "User organisations."
You can search on the left and click the plus to bring it to the right which makes sense. But after clicking the green button on the right to add a new organisation, it does not​ get associated with your account, you need to search for it again and click the plus. This is a bit unituitive because of the position of the plus, you'd typically expect the plus to add items near where it is located (on the right) but the plus adds them on the left. I would propose moving the new organisation to the left, below available organisations.
> To me, the green button caught my attention and I started adding my own organisation before I even noticed the presence of "available organisations;" to mitigate this you might even consider only showing the "add new organisation button" after the user has searched for their organisation.
