### ISSUE TITLE
Searches for front-page "Databases" entry point returns all registries

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1288]
**Describe the bug**
The URLs for the searches for the "Databases" box on the homepage are incorrect, pointing across all registries rather than databases only.

**To Reproduce**
1. Go to https://beta.fairsharing.org/
2. Scroll down to 'Databases'
4. See error for each of Natural Science, Engineering Science, Social Science, Humanities

**Expected behavior**
These search URLs should be for databases only, not across all of FAIRsharing.

**Screenshots**
![databases](https://user-images.githubusercontent.com/143586/137743525-599cadb5-827c-465f-8411-d37fe20e6bce.png)

**Operating system and browser version**
Ubuntu / Firefox

**Comment by allysonlister** [comment]
This search is now correct - thank you! However, the counts are still wrong (e.g. 2920 for Natural Science when it should be about 1600-ish). I've tried a forced refresh but the counts remain. Thanks!

I've reopened but please feel free to close if you need to tell me that I have somehow missed the fact that the numbers are correct :-)

**Comment by knirirr** [comment]
The counts provided are correct for the original URL. Now that I've changed the URLs the counts no longer match. I am not sure if there's a means to support the results for those new URLs without a custom hack for that particular part of the page. 

This will probably involve adding a separate search query for databases only and calling that rather than using the existing aggregations.
