### ISSUE TITLE
Not all relationships shown in Edit interface

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1292]
**Describe the bug**
A relationship is missing from the edit interface that is present in the record view.

**To Reproduce**
1. https://beta.fairsharing.org/1203
2. View shows all 4 relationships, in particular two relationships that both go to schema.org. Sometimes, this might be a valid piece of annotation and so I'm fine with both relationships being visible. However, the Edit interface only shows 3 of these relationships - one is missing. (Ultimately I would like to delete the "related to" relationship in favor of the "profiles" relationship but I won't do that until this is resolved

**Expected behavior**
All relationships a record has should be visible both in view and edit interfaces.

**Screenshots**
![schema2](https://user-images.githubusercontent.com/143586/138128732-7d7c6e8a-6d88-4984-8e44-8bee52bc823c.png)
![schema](https://user-images.githubusercontent.com/143586/138128733-bc629434-6538-4f52-9d8a-82221f4fa193.png)

**Operating system and browser version**
Ubuntu / Firefox

**Additional context**
This record already has the "related to" schema.org relationship. I updated the record by adding "profiles" without deleting the "related to" relationship. I noticed that although all relationships were visible in the record view, the "related to" relationship was not present in the edit interface.

Ultimately, I wish to delete the "related to" relationship, but will wait until this bug is resolved.

**Comment by knirirr** [comment]
Luckily this turns out not to be a bug. The additional relationship is an incoming one, and so won't appear in the edit interface:

<img width="540" alt="Screenshot 2021-10-26 at 14 22 28" src="https://user-images.githubusercontent.com/3583375/138888324-ed2e34d9-c91d-498c-859c-8317c1a799ca.png">

Because of such potential for confusion I did suggest organising these display elements differently, but the current arrangement was preferred.
