### ISSUE TITLE
Allow "Not available" for homepage URL for collections

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1395]
Some collections will never have a homepage. Therefore, to prevent us simply putting the same value for both homepage and reference URL, please can we have "Not available" as a valid string for the homepage field for collections?

Thanks!

**Comment by knirirr** [comment]
This will not be possible as it is described above.
"Homepage" is a compulsory field for all records which must validate as a URL. To make it optional or change its type is going to cause problems, as did removing status for collections (which was later reverted anyway). 
I see from a collection page (https://beta.fairsharing.org/3493) that the GeneralInfo section has been modified so that reference_url displays there, next to homepage. The request in this ticket could therefore be simulated by hiding "homepage" entirely, or displaying an N/A value, if reference_url is also defined.

**Comment by allysonlister** [comment]
Thank you! Please can you say "Not available" if the reference_url is identical to the homepage_url.

**Comment by hoseinmirian** [comment]
> reference_url

Define idetentical please!? to what extent? I mean the URL below as example:
<img width="663" alt="image" src="https://user-images.githubusercontent.com/25683981/147674037-ff90732c-4e59-4b4e-af35-efd451c718ce.png">


I think the best way is what s been said: "if both are defined, then I put Not Available for home page"

**Comment by allysonlister** [comment]
Thanks. That's not quite what I mean.

For those cases where homepage and reference URL are identical, the value displayed for the reference URL should be "Not available". As examples, take these:

* https://beta.fairsharing.org/3499
* https://beta.fairsharing.org/3518
* https://beta.fairsharing.org/3519

However, your statement that "if both are defined, put _Not Available_" is wrong. Both have to be defined, and both have to be identical. Many collections have both reference URL and homepage defined, but as different values. This ticket does not relate to them.
