### ISSUE TITLE
Update rules for square logos so that they also include "nearly" square logos

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1492]
**Describe the bug**
I really like our new ability to add logos. However, nearly square (but not exactly square) logos are treated in the same way as rectangles, which makes them very large.

**To Reproduce**
1. Go to https://beta.fairsharing.org/1442
2. See error

**Expected behavior**
When something is "nearly" square, the sizing should be applied as if it were square. Perhaps think about what the proportion of height and width are to get a good way of defining this.

**Screenshots**
![rocrate](https://user-images.githubusercontent.com/143586/151380966-c043c94d-880d-4853-a9f2-8567a6700e83.png)

**Operating system and browser version**
Ubuntu / Firefox

**Comment by allysonlister** [comment]
Please also note this rectangular logo that is a bit large as well, when thinking about how to compute logo size based on length/width ratio. Thanks!

https://beta.fairsharing.org/2163

**Comment by allysonlister** [comment]
Another example of a logo that has come out as too large: https://beta.fairsharing.org/3513

thanks!

**Comment by allysonlister** [comment]
Please note a few have commented on the size of logos that are closer to square, like these, especially on smaller screens. If someone could take a look at this ticket this week, that would be great, thanks!

**Comment by hoseinmirian** [comment]
@allysonlister I think its more a back-end related issue due to users upload different image sizes and resolution its very difficult to track and convert them in front end and it can be done in back-end using packages like 
https://www.npmjs.com/package/multer
@knirirr 

unless we ask users to upload a specific image size and resolution like 72dpi which is good for digital screens. this way we do not need a back-end resizing image process

**Comment by knirirr** [comment]
We can't use that package as it requires multipart form data, unfortunately. 
I suggest setting a maximum image size on the client and using "contain": https://vuetifyjs.com/en/components/images/#contain
