### ISSUE TITLE
Logo for community curators

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1585]
Please could you create a logo for community curators that could be applied to user profiles if they have the appropriate status?

I don't really know what it should look like, so perhaps you could provide maybe 2-3 ideas, and then I can ask our community curators for feedback? Thanks!

Please note this ticket is for the logo only, and not its integration into the user profile pages.

**Comment by knirirr** [comment]
Please note that our data model doesn't know about whether a user is specifically a _community_ curator. Currently, community curators belong to the curator role and our staff belong to other roles, so the distinction is still maintained. However, if there's ever likely to be a requirement that a member of the FAIRsharing team be assigned as a curator (instead of a "higher" role) then they'd also get this badge on their profile.

Of course, if the curator role is to be used only for community curators then this shouldn't be a problem.

**Comment by hoseinmirian** [comment]
I create 2 badge if @allysonlister is happy.. lets say we have 2 level of curator: normal curator which is a community and super curator... 


sounds good?

**Comment by allysonlister** [comment]
Thanks I hadn't thought of that. Please feel free to make both badges, but we may just start with visible badges for regular curators 🙂

**Comment by knirirr** [comment]
I'll close this as #1590 deals with applying the logo to users' pages.
