### ISSUE TITLE
500 error when adding organisation

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1654]
**Describe the bug**
Adding an organisation to a policy record results in 500 error.

**To Reproduce**
1. Go to https://fairsharing.org/3900/edit
2. Add the "MNHN" organisation (with "maintains" link)
3. Save and continue
4. See 500 error.

**Expected behavior**
Organisation should be added.

**Screenshots**
![mnhn](https://user-images.githubusercontent.com/143586/165959863-5df72a93-a735-4d6a-b6e9-340d096670ab.gif)

**Comment by knirirr** [comment]
This is because that organisation (2051) no longer exists, having been deleted in the RoR update. A reference to it has persisted in the Elasticsearch indexes, though. A full reindex will take the site down for an hour so I'll investgate another means to clear these entries before resorting to that.
How any deleted organisations are still in Searchkick is unclear; the modification script should have triggered Searchkick to delete these references.

**Comment by knirirr** [comment]
I've run @ramGranell 's fix and the indexes look up to date.
