### ISSUE TITLE
Redirections for SRAO URLs please

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1741]
As pointed out [here](https://github.com/FAIRsharing/subject-ontology/issues/72), it seems I have forgotten to put redirections in place for the SRAO URLs.

Please could you set up the following?

http://www.fairsharing.org/ontology/subject/SRAO.owl -> https://github.com/FAIRsharing/subject-ontology/raw/master/releases/SRAO.owl

http://www.fairsharing.org/ontology/subject/SRAO.owl/0.3.0 -> https://github.com/FAIRsharing/subject-ontology/raw/master/releases/0.3.0/SRAO.owl

Thank you!

**Comment by knirirr** [comment]
There is already a route set up which does:

https://fairsharing.org/ontology/srao -> https://github.com/FAIRsharing/subject-ontology
https://fairsharing.org/ontology/drao -> https://github.com/FAIRsharing/domain-ontology

Are the new routes mentioned above to be instead of or as well as the existing ones?

**Comment by allysonlister** [comment]
As well as, please. 

Thanks!
