### ISSUE TITLE
Cross References not displaying their note text

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#2021]
**Describe the bug**
Cross references are displaying hyperlinked URLs, but where a note is present, the note string should be hyperlinked using the URL value

**To Reproduce**

https://doi.org/10.25504/FAIRsharing.pdwqcr
![image](https://user-images.githubusercontent.com/143586/220310240-d3a4b74c-9d1e-4b48-8fd6-e451acf51367.png)
![image](https://user-images.githubusercontent.com/143586/220310632-ce6543e5-5442-4dde-b60e-4edcd25b1938.png)

You can see there are notes, but they're not being displayed

Thanks!

**Comment by knirirr** [comment]
I'm not 100% sure I've understood this, but do you mean that instead of seeing the two URLs seen there you would like to see some text which is a hyperlink to those same URLs? If so, would that be the "name" text (there isn't a notes field)?

If so then this isn't a bug, and may not be possible without extensive re-working of the AdditionalInfo component (but I will look).

**Comment by allysonlister** [comment]
Sorry, I meant "name". 

Yes, "name" isn't being shown right now at all in the UI, so I was asking if we could use the name, where present, as the display text with the hyperlink being the URL field.

If it will require a lot of work, feel free to make it low priority and do it at a more convenient time. Thanks!

**Comment by knirirr** [comment]
A deeper look into this revealed that the code was dodgy after all - my fix (PR to follow) makes it do what it should have done in the first place, which is not exactly what you asked for here but still does show the name field.
