### ISSUE TITLE
New tools

### ISSUE THREAD

**Issue by knirirr** [FAIRsharing/fairsharing.github.io#2027]
This ticket is to add his response to the tools questionnaire into the relevant JSON for the site.

@allysonlister we don't have an organisation entry for https://fairdata.systems/home/ (Mark Wilkinson)- how would you like to handle that? Presumably it could be created and assigned to Mark, but I am not sure to which records it should be linked and how.

**Comment by allysonlister** [comment]
This is a really good point, actually. In theory, organisations don't have to be added to a record, just to a user. Let me add it to his user profile at https://fairsharing.org/users/866 (as this is the profile with the same email as listed in the form), and then you can use that one.

Ugh, or I would add the organisation to the user's profile, but I can't because orgs now require countries, and the "New Org" form that curators have access to from a user's profile doesn't have a country field.

I will cheat by adding the org to my account, then removing it, then adding it to Mark's.... Please could you see about creating a ticket to add a country field to that "new org" popup that curators see? As only internal curators see it, and we don't use it often, this can be a low priority ticket.

The organisation is now present in the system as https://fairsharing.org/organisations/3899

thanks!

**Comment by knirirr** [comment]
Other responses have since come in and so these could be added as part of this ticket.

**Comment by knirirr** [comment]
I'll close this in favour of https://github.com/FAIRsharing/fairsharing.github.io/issues/1927, as the question about Mark's organisation has been resolved.
