### ISSUE TITLE
Adding an anchor for each tile

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#2029]
As suggested by @cthoyt, please can we add anchors for each tools tile such that each tool has a URL that goes directly to their tile on the page so that they - and we - can share it on social media etc?

Something like https://fairsharing.org/communities#toolName or similar?

Thanks!

**Comment by knirirr** [comment]
This has been done and can be merged to master with the entries from the Google forms which @ramGranell has been entering.

**Comment by cthoyt** [comment]
Dear @knirirr, I notice that your process of merging PRs into the `dev` branch then later into the `master` branch throws away git attribution of the contributors. This is not an ideal situation, as there is no reflection that myself nor others who have contributed have done so in the `master` branch's git history, and therefore not on GitHub.

(alternatively, this was marked as complete prematurely, since it appears  #2034 will actually hold the changes. I hope that what I mentioned isn't an issue going forward, thanks).

**Comment by knirirr** [comment]
@cthoyt at the time you commented I hadn't done that merge. Now that I have, you can be seen amongst the contributors, here:

https://github.com/FAIRsharing/fairsharing.github.io/blob/master/src/views/Static/Community/Community.vue

So, there is no problem with the process.

**Comment by cthoyt** [comment]
@knirirr thanks
