### ISSUE TITLE
Advanced search interface

### ISSUE THREAD

**Issue by knirirr** [FAIRsharing/fairsharing.github.io#2139]
This involves creating a parallel and separate searching system based around the vuetify query builder: ~https://npm.io/package/vue-query-builder-vuetifyjs~
https://www.npmjs.com/package/query-builder-vue?activeTab=readme

A separate ticket will be created for the relevant routes on the server to handle the clients' queries.
- [x] Advance Search button to navigate to separate search page.
- [x] Separate search page based on the package above.
- [x] Separate results page based on existing FAIRsharing code.

**Comment by knirirr** [comment]
Fields for advanced search (which will no doubt be revised on a few occasions to come are):


-   taxonomy (autocomplete) - use searchTaxonomy query
-   data access condition (fixed options)
-   data deposition condition (fixed options)
-   data curation (fixed options)
-   record status (fixed options)
-   domain (autocomplete)
-   user defined tag (autocomplete)
-   licence (autocomplete) -- field yet to be added in ```advancedSearch``` query - https://github.com/FAIRsharing/FAIRsharing-API/issues/870
-   organisation (autocomplete) -- field yet to be added in ```advancedSearch``` query - https://github.com/FAIRsharing/FAIRsharing-API/issues/870
-   subjects (autocomplete)
-   Registry (fixed options)
-   Type (fixed options) 

Ref: https://zulip.fairsharing.org/#narrow/stream/13-FAIRsharing-Development/topic/Advanced.20search/near/51962

FAO @prakhyatox

**Comment by allysonlister** [comment]
This is looking great! Sorry for the delay this week... Some thoughts now that we're reaching the end of this piece of work. You'll notice that all of these thoughts aren't around the advanced search functionality itself - I have yet to find an issue with the search itself!

I'll continue looking later today or early next week, but I think these are good to be getting on with.
@delphinedauga and @ramGranell do you have the time to do a similar review please?

- [x] Please could the either "and" or "or" that joins items in the blue pills be shown instead of a comma? e.g. in this example "Databases or Standards"?
![image](https://github.com/FAIRsharing/fairsharing.github.io/assets/143586/5976f8e0-8de6-4472-9125-05ecefbf66e5)
- [x] Some of the rule types don't have spaces, when others do. Please could you add spaces as appropriate throughout? e.g. DataCuration --> Data Curation
![image](https://github.com/FAIRsharing/fairsharing.github.io/assets/143586/c4ede2a0-8c7a-425f-9004-c138fd171e30)
- [x] Can "Add Group" float? Once I've got lots of search terms, it disappears off the top of the window and I need to scroll up and down to first add a group and then scroll down again to modify it.
- [x] If the Registry rule is enabled AND none of the registries chosen includes Databases, then the options that are pertinent to the Database fields should be greyed out and impossible to select. In the example below, only standards have been selected, so Data Curation, Data Deposition, and Data Access should be greyed out / not present. If this is too hard to implement at this stage, we need very clear statements in the documentation that this will cause mayhem if selected as it will ensure any query that does NOT include databases will return zero results unless with an "OR". --- ```This won't be possible to implement because the none of query builder component which is used for such complex AND/OR combination supports customisation. The only option we have to write in gitbook explaining the the behaviour and functionality of the Advanced Search```
![image](https://github.com/FAIRsharing/fairsharing.github.io/assets/143586/f9d95a3a-ddba-4676-9d92-2b37a05b2c41) 
- [x] Clicking on any link in the results page takes me to https://deploy-preview-2188--fairsharing.netlify.app/NaN rather than the proper results page.


- [x] Could the pills that show the multiple items you've chosen from your rule group have the AND or OR written between them as you're building the query? I realise that the Operator pulldown gives you this info, but it would make it clearer what that operator refers to. A bit like this: --- ```This won't be possible since it is a dropdown from Vuetify and it does not have scope for customisation```
![image](https://github.com/FAIRsharing/fairsharing.github.io/assets/143586/f041fe1c-93c4-499f-ad6b-c6b291d6f43e)
- [x] You'll need to add some documentation to gitbook about how it functions, and then link it to the top of the advanced search box. If you've not added stuff to gitbook before, just write some text in a google doc and we can go over the gitbook part later on together
- [x] Could we have a link/button/some method of opening the advanced search in a new page as well? The pop up is nice, but it would also be good to have it open in a new page. --- ```Instead of having search in new page, popup will cover fullscreen so it looks like a new page which seems to be better UX fix```
- [x] Tooltips with "?" next to every section/button you can think of. I suggest you write them in the first instance, and then I provide any thoughts, seeing as you know best how they work.
- [x] Is it possible to have the pagination stuff on both the top and bottom of the search results page?
![image](https://github.com/FAIRsharing/fairsharing.github.io/assets/143586/11bba55d-bd89-4048-b0f9-27fa6a2314cb)
- [x] Can there be a download button as there is in the older search results page?
- [x] Can there be a button under "Edit Advanced Search" that would say "Clear Advanced Search and Start Again" or similar? I realise the user could just click on Advanced Search at the top of the page, but I feel like there ought to be that functionality closer to the Edit Advanced Search too.

**Comment by knirirr** [comment]
- [x] I've added a line through the name of deprecated search results (see https://github.com/FAIRsharing/fairsharing.github.io/issues/2212). If this is kept then it would be useful to do something similar in advanced search results.

**Comment by allysonlister** [comment]
I was editing an existing advanced search with a maximised window:
![image](https://github.com/FAIRsharing/fairsharing.github.io/assets/143586/e33d692c-8e3c-4e64-a7a5-1eca853a2c28)


And then I shrank the window to about half of my monitor size. Immediately my edit screen for the advanced search disappeared, replaced with the last output of my "proceed" button press:
![image](https://github.com/FAIRsharing/fairsharing.github.io/assets/143586/7585cfd1-000c-45a2-b0b8-4db2008dfadd)

There are three issues here:
- [x]  When I shrink the window, the edits I'm doing to the advanced search disappear and are replaced by the previous search results. I can get back to it by clicking on Edit Advanced Search but I shouldn't have to do that.
- [x] I then try to use the "Advanced Search" button to the right of "Edit Advanced Search" to restart my advanced search, but the first time I press it, my OLD search (instead of a blank search) appears. If I close the window and then press "Advanced Search" again, it opens an empty advanced search.
- [x] When I shrink a search results window, the left-hand bar containing my current filter set disappears and I can't find it anywhere in the window, even with scrolling.


Separately:

- [x] In the search results page next to "Edit Advanced Search" please rename "Advanced Search" to "Restart Advanced Search"


- [x] Then I try to reset EVERYTHING by clicking on "Advanced Search" in the top toolbar. I am presented correctly with an empty advanced search, but when I am building a query, see that when I choose "Subject" and click on the empty field, I am presented with a single autocomplete of "Humanities and Social Science", which is the value I chose previously. Very odd. --```This feature is caching. It will keep the previously selected items of the users for the autocomplete field. If you would like, I could remove this feature.``` _for now, let's keep it and see what our testers say, thanks!_
![image](https://github.com/FAIRsharing/fairsharing.github.io/assets/143586/dcd5ef99-91c4-4911-8769-94bbb5ea8679)


Happy to show you this over skype if it's easier.

**Comment by allysonlister** [comment]
What does the "add search text" do? I type something in and press return and nothing happens... and there is no tooltip---```If user wants to add some text for advanced search , they can add the text and then proceed with the selection. This field is only present while editing the advancedSearch. We can either add the tooltip here or can remove this field.```

**Comment by allysonlister** [comment]
We really need some additional tooltips, as they've only been added to the blue sections and not the grey ones.

![image](https://github.com/FAIRsharing/fairsharing.github.io/assets/143586/11e6d080-659e-4304-879d-fa0f25537c40)

1. can the tooltips in the blue ones change based on the value of the blue? e.g. one tooltip for if the rule is Registry, and another tooltip if the rule is Subject? That will help me write my text
2. The grey operator section for the Add Group block should have a tooltip that says "Connect each group of rules with either "AND" or "OR"."
3. All other grey operator sections should have a tooltip that says "Connect the rules inside this group with either "AND" or "OR."

If there can only be one tooltip across all blue "rules", then have it say: "Select those value(s) that you wish applied to your search. Note that each item within this rule will be joined with an "OR"."

**Comment by allysonlister** [comment]
> If the Registry rule is enabled AND none of the registries chosen includes Databases, then the options that are pertinent to the Database fields should be greyed out and impossible to select. In the example below, only standards have been selected, so Data Curation, Data Deposition, and Data Access should be greyed out / not present. If this is too hard to implement at this stage, we need very clear statements in the documentation that this will cause mayhem if selected as it will ensure any query that does NOT include databases will return zero results unless with an "OR". --- `This won't be possible to implement because the none of query builder component which is used for such complex AND/OR combination supports customisation. The only option we have to write in gitbook explaining the the behaviour and functionality of the Advanced Search`

![image](https://github.com/FAIRsharing/fairsharing.github.io/assets/143586/15bd96c8-8c5a-4614-b431-8726e05651f8)

- [x] In relation to the above, I suggest that in addition to the gitbook documentation that you modify those Rule labels I list below as follows (all other rules can remain as-is):
* Data Curation - Databases only
* Data Deposition Condition - Databases only
* Data Access Condition - Databases only
- [x] Please move these three down to the end of the pulldown menu.

**Comment by allysonlister** [comment]
Just going through all comments now, but noticed this bug (in Firefox)

I open up the build, and click advanced search, then put this info in: -- ```Fixed```
![image](https://github.com/FAIRsharing/fairsharing.github.io/assets/143586/fc2cefca-583f-45d7-b421-d06d9f97bcd4)

I click Proceed, and then instead of the search running, the fullscreen popup closes, revealing another empty popup directly under it. ~~No search is performed.~~ The search is performed and shown correctly, but I must close the empty  popup that is "underneath" first
![image](https://github.com/FAIRsharing/fairsharing.github.io/assets/143586/89b7cb45-31ca-4929-a534-14f26f6a0d07)

**Comment by allysonlister** [comment]
FYI: ~~No search is performed.~~ The search is performed and shown correctly, but I must close the empty  popup that is "underneath" first --```Fixed```

**Comment by allysonlister** [comment]
> What does the "add search text" do? I type something in and press return and nothing happens... and there is no tooltip---`If user wants to add some text for advanced search , they can add the text and then proceed with the selection. This field is only present while editing the advancedSearch. We can either add the tooltip here or can remove this field.`

Thank you - but it's not clear how it's connected to the rest of the search section. Is it AND with everything else, or OR? It makes sense for it to be AND, and that seems to be what is happening in the results, but neither the query builder nor the left-hand summary show the connection. It looks like it is essentially added as another "group" of one text field? Please could you add text about the AND to both the tooltip and as a similar pill in the search results to the other ANDs...? e.g. the orange AND pill? ---```I tried to explain what the add search textfield does with advancedsearch but I didn't understand your comment. Maybe we can discuss this over the call```

**Comment by allysonlister** [comment]
> * When I shrink the window, the edits I'm doing to the advanced search disappear and are replaced by the previous search results. I can get back to it by clicking on Edit Advanced Search but I shouldn't have to do that.

Although this was ticked, I can't see the fix in this build at https://deploy-preview-2188--fairsharing.netlify.app/ . Additionally, when the advanced search popup disappears, clicking on 'Edit Advanced Search' doesn't bring it back at all.--```Fixed```

If it's easier, and less buggy, would one possible solution be to have the query builder in the top of the search results page, underneath the banner (and allow it to be minimizable), and then we don't need a popup at all?

**Comment by allysonlister** [comment]
> * I then try to use the "Advanced Search" button to the right of "Edit Advanced Search" to restart my advanced search, but the first time I press it, my OLD search (instead of a blank search) appears. If I close the window and then press "Advanced Search" again, it opens an empty advanced search.

This is also still happening for me--```Fixed```

**Comment by allysonlister** [comment]
> * When I shrink a search results window, the left-hand bar containing my current filter set disappears and I can't find it anywhere in the window, even with scrolling.

This is also still happening.--```The left-hand bar is hidden in mobile because of the limited space. If you will notice the Edit Advanced Search will say Show/Edit Advanced Search in mobile. The similar thing is done in the Search where left hand bar is hidden and replaced by Show Filters button```
