### ISSUE TITLE
Saved Search: generated link not re-creating the adv search properly

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#2385]
Hiya! I just noticed that the saved search in my profile (https://fairsharing.org/users/579) doesn't get re-created properly when you click on it.

The URL it has saved is https://fairsharing.org/advancedsearch?operator=_and&fields=%28operator%3D_and%26registry%3Dpolicy%26recommendsDatabase%3Dtrue%26recommendsStandard%3Dtrue%26sharingResearchSoftware%3Drequired,suggested%26mandatedDataSharing%3Drequired,suggested%29 but when I click on the link , it returns zero results instead of 69:

![image](https://github.com/user-attachments/assets/6f44b466-919a-4001-a22c-f8b3dc39b057)

When I build the search again from scratch, the query correctly returns 69 records:
![image](https://github.com/user-attachments/assets/27f7e9b4-acb7-4440-8cb1-14fd0f777834)
![image](https://github.com/user-attachments/assets/25ef1ec7-ee6b-4bde-bd21-ca6cee0b1bad)

Not quite sure what's happening here - perhaps the saved search on my profile was from when we were still creating the feature, and so the URL isn't correct?

I tried saving this second search so we could compare them both on my profile, but for some reason the Save button remains determinedly grey and I can't click it:
![image](https://github.com/user-attachments/assets/7b0f8f5e-7668-4476-9964-582df88cff0b)

However, the URL in the browser for this second search is https://fairsharing.org/advancedsearch?operator=_and&fields=%28operator%3D_and%26registry%3Dpolicy%26recommendsDatabase%3Dtrue%26recommendsStandard%3Dtrue%26sharingResearchSoftware%3Drequired,suggested%26mandatedDataSharing%3Drequired,suggested%29 so perhaps this helps?

Thanks!

**Comment by prakhyatox** [comment]
1) Save button issue is fixed
2) With regards to URL generated to save the search there is a change in the URL generation when the search is generated/saved (refer PR https://github.com/FAIRsharing/fairsharing.github.io/pull/2383) to see the change

- Earlier when the was URL generated, the fields which had multiple selections were seprated by comma (,) which were causing any single selection having comma to break into different words

    > e.g. If selection for `Organisation` = `(University of Oxford, Oxford)` `(University of Cambridge, Cambridge)` it was converted to `(University of Oxford)`, `(Oxford)`, `(University of Cambridge)`, `(Cambridge)`
    > 
    > Happening in above case: https://fairsharing.org/advancedsearch?operator=_and&fields=(operator=_and&registry=policy&recommendsDatabase=true&recommendsStandard=true&sharingResearchSoftware=required,suggested&mandatedDataSharing=required,suggested)

- Now when the URL is generated the multiple selection is joined by character `+` instead of `,` which does not break the word having comma in it

     > https://fairsharing.org/advancedsearch?operator=_and&fields=(operator=_and&registry=policy&recommendsDatabase=true&recommendsStandard=true&sharingResearchSoftware=required+suggested&mandatedDataSharing=suggested+required)

This why the older saved with multiple selection in one field might not work

P.S: Don't try above URL directly into the browser as they are decoded and will not give the results using them directly in the address bar of the browser

**Comment by allysonlister** [comment]
OK that's great to know! Will look at the related PR now
